### ISSUE TITLE
Inheriting definitions causes 500 error on updating of the inherited fields

### ISSUE THREAD

**Issue by SoetZombie** [Ucommercenet/Ucommerce-Seeder#9]
Steps to reporduce:

- Seed the database
- inherit definition ( I was inheriting it on default category definition)
- try to change inherited definition field in the UI

**Comment by skovsboll** [comment]
I can't repro this. Tried with catalogs, products and variants.
Is it a problem in the legacy UI (which has now been replaced), or the new?
If you can repro, please add more details about the error, @SoetZombie.

**Comment by SoetZombie** [comment]
> I can't repro this. Tried with catalogs, products and variants.
> Is it a problem in the legacy UI (which has now been replaced), or the new?
> If you can repro, please add more details about the error, @SoetZombie.

If I was about to guess this issue was solved as a part of bugfix a while ago. And yes it was the legacy UI, therefore I will close this issue. Completely forget about it.
